version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
  install:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  lint:
    steps:
      - run: npm run lint:ci
  test:
    steps:
      - run: npm run test:ci
  danger:
    steps:
      - run: npm run danger

workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires: [install]
      - test
          requires: [lint]
      - dagger
          requires: [test, lint]
