version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:ba:f6:b5:1f:73:72:c8:3d:71:6a:0f:e3:08:ab:61"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules\
      - run:
          name: lint
          command: npm run lint:ci
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: pre-danger
          command: git config user.email "drodriguez@smartprocure.us" && git config user.name "Decrapifier" && git config push.default current
          when: always
      - run:
          name: danger
          command: npm run danger
          when: always
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish
            fi
